### ISSUE TITLE
Release schedule

### ISSUE THREAD

**Issue by benesch** [andygrove/sqlparser-rs#117]
Extracting discussion from #105: 

> We should also talk a release schedule at some point. The last release was 2 months ago apparently.

We have [at least one user](https://github.com/andygrove/sqlparser-rs/issues/67#issuecomment-500934474) who's requested a new release. Some options:

* Follow the Rust approach of releasing every _n_ weeks, regardless of what's ready and what's not.
* Aim for a regular cadence, but tie the release to the readiness of certain issues/features/whatever.
* Release when the list of unreleased features piles up sufficiently; basically, whenever users are asking for it.

@nickolay @andygrove thoughts?

**Comment by nickolay** [comment]
As I said in #105 I think we should finish up the renames, then make a release. Otherwise anybody who tries out the version from crates.io will have to deal with the major changes made in the last two months and/or with the changes from #105.

Going forward I think it's up to whoever publishes the releases, since the options you listed vary in terms of time required on their part. I guess the default option is No.3 ;)

**Comment by benesch** [comment]
Well, the renames are done! Is it time for a release?

**Comment by nickolay** [comment]
Thanks! I think it's up to @andygrove now, as he owns the package on crates.io.

**Comment by andygrove** [comment]
Ack. I will create a release this week. Is this a new major version ?

**Comment by nickolay** [comment]
@andygrove Thanks! Yep, I think it ought to be bump to 0.4, given the amount of improvements and incompatible changes landed since April by @benesch and others.

Going forward should we always bump the minor version (i.e. 0.5, 0.6, etc.), given that pretty much every change we make isn't backwards compatible and the [Cargo book recommends avoiding breaking changes in "patch" releases](https://doc.rust-lang.org/cargo/reference/manifest.html#the-version-field)?

**Comment by andygrove** [comment]
0.4 is released :tada:

**Comment by benesch** [comment]
> Going forward should we always bump the minor version (i.e. 0.5, 0.6, etc.), given that pretty much every change we make isn't backwards compatible and the Cargo book recommends avoiding breaking changes in "patch" releases?

Yep, that makes sense to me. It would be an unusual situation indeed that resulted in a patch release. The only thing I can envision is a bug fix to the parser that doesn't require any changes to the AST.

Going to close this out, since I think the strategy of "release whenever things pile up" will work alright for the time being.
