### ISSUE TITLE
SQL:2016

### ISSUE THREAD

**Issue by davidfetter** [andygrove/sqlparser-rs#125]
There's a new version of the standard, so it'd be great to catch up with it.

**Comment by nickolay** [comment]
Hey, thanks for taking an interest in the project!

I guess (@andygrove might correct me) the reason the stated goal of this project is to be compatible with ANSI SQL 2011 is because that's the latest version of the standard with [its grammar available online in HTML format](https://jakewheat.github.io/sql-overview/sql-2011-foundation-grammar.html).

I don't think we've implemented all of SQL-92 yet (though thanks to @benesch we're getting close), and there's lots of work to catch up with SQL 2011, so it's a bit too early for SQL 2016!

If you'd like to contribute implementations, testcases, or links to the grammar for some of [the 44 new features](https://modern-sql.com/blog/2017-06/whats-new-in-sql-2016), that would be in scope for this project, I think. Otherwise, I'm in favor of closing this issue as I believe it's not actionable due to its large scope. Andy, Nikhil, what do you think?

**Comment by benesch** [comment]
Agreed. The SQL standard is massive, and plenty of it isn't even supported by any actual databases. The only sane way to make progress is to prioritize the specific features that folks are interested in.

I'd be in favor of updating the wording in the README a bit, though. Perhaps something like:

> The goal of this project is to build a SQL lexer and parser capable of parsing SQL that conforms with the [ANSI/ISO SQL standard](https://en.wikipedia.org/wiki/ISO/IEC_9075) while also making it easy to support custom dialects so that this crate can be used as a foundation for vendor-specific parsers.
>
> SQL was first standardized in 1987, and revisions of the standard have been published regularly since. Most revisions have added significant new features to the language, and as a result no database claims to support the full breadth of features. This parser currently supports most of the SQL-92 syntax, plus some syntax from newer versions that have been explicitly requested, along with some MSSQL- and PostgreSQL-specific syntax. Whenever possible, the [online SQL:2011 grammar](https://jakewheat.github.io/sql-overview/sql-2011-foundation-grammar.html) is used to guide what syntax to accept.

Let me whip up a PR!

**Comment by benesch** [comment]
FWIW, I've submitted a PR to get the SQL:2016 grammar online: https://github.com/JakeWheat/sql-overview/pull/2. Unfortunately @JakeWheat hasn't been active lately, but hopefully it'll get deployed eventually.

**Comment by benesch** [comment]
Thanks to @JakeWheat, we've now got the grammar online! https://jakewheat.github.io/sql-overview/sql-2016-foundation-grammar.html

**Comment by benesch** [comment]
Closing this out because, as @nickolay mentioned, I don't think it's actionable, and the policy is now more fully spelled out in the README. Please feel free to open PRs/issues for any SQL:2016 features that you need.
