### ISSUE TITLE
CREATE INDEX?

### ISSUE THREAD

**Issue by budleigh** [andygrove/sqlparser-rs#152]
Not sure if I'm misusing things or misunderstood (it does look like index operations of any kind are not defined in the SQL specs I've peeked at), but is there a particular reason that it's currently not possible to parse a CREATE INDEX/DROP INDEX statement?

**Comment by nickolay** [comment]
Sorry for the late answer!

Yes, `CREATE INDEX` is not part of ANSI SQL because like much of DDL it's very database-specific.

`sqlparser` doesn't support it simply because no-one implemented it. At this point we accept PRs that add support for syntax accepted by a popular RDBMS, so if anyone is willing to implement any part of it, it would be great.

**Comment by mashuai** [comment]
Add CREATE INDEX AND DROP INDEX support. https://github.com/andygrove/sqlparser-rs/pull/167

**Comment by nickolay** [comment]
Thanks to @mashuai, PR #167 is now merged, and sqlparser supports CREATE/DROP INDEX (to the extent described in that pull request). I think I'm going to close this issue.
