### ISSUE TITLE
Redshift interval literals seem to fail to parse

### ISSUE THREAD

**Issue by maxcountryman** [andygrove/sqlparser-rs#177]
[Redshift's interval literals](https://docs.aws.amazon.com/redshift/latest/dg/r_interval_literals.html) seem to differ in structure from what the parser presently expects. Notably, the date/time field is part of the preceding string. Perhaps the interval implementation could be modified to consider the Redshift implementation?

**Comment by nickolay** [comment]
This was [intentional limitation of the initial implementation](https://github.com/andygrove/sqlparser-rs/pull/103#discussion_r291827496) and there's [a note to that effect in parser.rs](https://github.com/andygrove/sqlparser-rs/blob/5f3c1bda0133348a0b60f18c88a0d48b9400dcfe/src/parser.rs#L526). I don't see a reason why we can't change the parser to accept `INTERVAL 'value'` not followed by YEAR/HOUR/etc.

(I'm curious how Redshift parses `select INTERVAL '1 day' DAY`.)

**Comment by maxcountryman** [comment]
I'd be happy to take a look at this, @nickolay.

**Comment by nickolay** [comment]
@maxcountryman That's great to hear! And I will be happy to merge a PR from you:)
