### ISSUE TITLE
Qualified wildcard to_string() is invalid

### ISSUE THREAD

**Issue by thomas-jeepe** [andygrove/sqlparser-rs#52]
Line in question: https://github.com/andygrove/sqlparser-rs/blob/master/src/sqlast/mod.rs#L114

Calling to_string() on a qualified wildcard returns `Qualification*` instead of `Qualification.*`. Should be as simple as changing the line to: `q.join(".") + ".*"`

**Comment by nickolay** [comment]
Thanks! While this fix should probably be applied anyway, I wonder how you found this.

Do you know which dialects allow qualified wildcards "inside" expressions, like `count(foo.*)` in your PR's testcase? ANSI SQL [defines](https://jakewheat.github.io/sql-overview/sql-2011-foundation-grammar.html#_10_9_aggregate_function) `<aggregate function> ::= COUNT <left paren> <asterisk> <right paren> ...`, MSSQL agrees by reporting a syntax error in `count(foo.*)`, and the construct doesn't make sense to me. I guess `COUNT(distinct foo.*)` could make sense, but I don't know of a RDBMs that supports that either.

(The widely supported `SELECT foo.*` is handled correctly now, because we convert `ASTNode::SQLQualifiedWildcard` to `SQLSelectItem::QualifiedWildcard` [here](https://github.com/andygrove/sqlparser-rs/blob/bbf1805729d4fb0238c889d258b092e64ad4bcad/src/sqlparser.rs#L1560) -- I was initially confused how this was not caught by an existing test.)

**Comment by thomas-jeepe** [comment]
I am not too sure exactly which databases support it, but it is a valid syntax.

[Stack overflow link recommending its use.](https://stackoverflow.com/questions/2710621/count-vs-count1-vs-countpk-which-is-better)

**Comment by nickolay** [comment]
Thanks! no need to test, I was wondering if you knew one off-hand. Turns out Postgres [does support it](https://www.db-fiddle.com/f/j1ykWCPKzPpko966NUmweR/0), though I didn't find it mentioned in their docs.

**Comment by nickolay** [comment]
The PR was merged. Thanks again!
